[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "pycountry>=24.6.1",
    "requests>=2.32.3",
    "rich>=13.9.4",
]
